version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    volumes:
      - taskpl_workspace:/srv
    ports:
      - "9646:80"

  taskpl:
    container_name: taskpl
    image: williamfzc/taskpl
    restart: always
    volumes:
      - taskpl_workspace:/taskpl_workspace
    ports:
      - "9647:9410"

  taskpl-dashboard:
    container_name: taskpl-dashboard
    image: williamfzc/taskpl-dashboard
    restart: always
    ports:
      - "9648:8010"
    depends_on:
      - taskpl

volumes:
  taskpl_workspace:
