version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.0.12
    restart: always
    volumes:
      - taskpl_workspace:/srv
    ports:
      - "20316:80"

  taskpl:
    container_name: taskpl
    image: williamfzc/taskpl
    restart: always
    volumes:
      - taskpl_workspace:/taskpl_workspace
    ports:
      - "20317:9410"

  taskpl-dashboard:
    container_name: taskpl-dashboard
    image: williamfzc/taskpl-dashboard
    restart: always
    ports:
      - "20318:8010"
    depends_on:
      - taskpl

volumes:
  taskpl_workspace:
