version: '3'
services:
  fileserver:
    container_name: fileserver
    image: williamfzc/min_file_server
    restart: always
    volumes:
      - taskpl_workspace:/usr/share/nginx/files
    ports:
      - "9645:80"

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.0.12
    restart: always
    volumes:
      - taskpl_workspace:/srv
    ports:
      - "9646:80"

  taskpl:
    container_name: taskpl
    image: williamfzc/taskpl
    restart: always
    volumes:
      - taskpl_workspace:/taskpl_workspace
    ports:
      - "9647:9410"

  taskpl-dashboard:
    container_name: taskpl-dashboard
    image: williamfzc/taskpl-dashboard
    restart: always
    ports:
      - "9648:8010"
    depends_on:
      - taskpl

volumes:
  taskpl_workspace:
